### ISSUE TITLE
Unable to install on fresh Ubuntu Server 18.04.4 LTS (Bionic Beaver)

### ISSUE THREAD

**Issue by v-oleksandr** [markusressel/cli2telegram#1]
**Describe the bug**
Hi, I'm unable to install cli2telegram package on my freshly installed ubuntu server 18.04.4 lts

**To Reproduce**
1. install pipe
```sudo apt install python-pip```
2. try to install cli2telegram
```pip install cli2telegram```

**Expected behavior**
should successfully install

**Tracelog**
```
pip install cli2telegram
Collecting cli2telegram
  Using cached https://files.pythonhosted.org/packages/93/dd/b2e5d0041b2e7318365b74ee7b4eb0c7ff1ab420e02902748e71010f6cea/cli2telegram-1.0.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-GkD8kJ/cli2telegram/setup.py", line 52
        def readme_type() -> str:
                          ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-GkD8kJ/cli2telegram/
```

**Desktop (please complete the following information):**
 - OS: ubuntu server 18.04.4 LTS

**Additional context**
Python version: 2.7.17

**Comment by v-oleksandr** [comment]
Ok... As I see it supports only Python 3 and above, so to fix it I need:

1. sudo apt install -y python3-pip
2. use pip3 install cli2telegram

Now everything works.
